services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_NAME=API Auditoria
      - DEBUG=false
    restart: unless-stopped
