services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-auditoria
    ports:
      - "8710:8710"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
